apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4mb0-kafka-consumer
  labels:
    app: l4mb0-kafka-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: l4mb0-kafka-consumer
  template:
    metadata:
      labels:
        app: l4mb0-kafka-consumer
    spec:
      containers:
        - name: consumer
          image: gcr.io/secteam/l4mb0-kafka-consumer:v4
          env:
            - name: KAFKA_TOPIC
              value: "messages"
            - name: KAFKA_ADDR
              value: "kafka.kafka:9092"
            - name: CONSUMER_GROUP
              value: "securecode"
