apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4mb0-kafka-producer
  labels:
    app: l4mb0-kafka-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: l4mb0-kafka-producer
  template:
    metadata:
      labels:
        app: l4mb0-kafka-producer
    spec:
      containers:
        - name: producer
          image: gcr.io/secteam/l4mb0-kafka-producer:v8
          env:
            - name: KAFKA_TOPIC
              value: "messages"
            - name: KAFKA_ADDR
              value: "kafka.kafka:9092"