apiVersion: v1
kind: Service
metadata:
  name: l4mb0-kafka-producer
spec:
  selector:
    app: l4mb0-kafka-producer
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP